// Nouns: 105 required + additional from PDF
export const nouns = [
  ['爱情','tình yêu','他们的爱情很美好。','Tình yêu của họ rất đẹp.'],
  ['笔记本','sổ tay','我在笔记本上记了很多笔记。','Tôi đã ghi nhiều ghi chú vào sổ tay.'],
  ['饼干','bánh quy','她喜欢吃饼干。','Cô ấy thích ăn bánh quy.'],
  ['博士','tiến sĩ','他是一位博士。','Anh ấy là một tiến sĩ.'],
  ['材料','tài liệu','这些材料很有用。','Những tài liệu này rất hữu ích.'],
  ['传真','fax','请把文件传真给我。','Xin fax tài liệu cho tôi.'],
  ['窗户','cửa sổ','请打开窗户。','Xin mở cửa sổ.'],
  ['词典','từ điển','我买了一本汉语词典。','Tôi đã mua một cuốn từ điển tiếng Trung.'],
  ['答案','đáp án','你知道答案吗？','Bạn biết đáp án không?'],
  ['大夫','bác sĩ','大夫说要多休息。','Bác sĩ nói cần nghỉ ngơi nhiều.'],
  ['大使馆','đại sứ quán','大使馆在北京。','Đại sứ quán ở Bắc Kinh.'],
  ['代表','đại diện','他是我们的代表。','Anh ấy là đại diện của chúng tôi.'],
  ['刀','dao','这把刀很锋利。','Con dao này rất sắc.'],
  ['导游','hướng dẫn viên','导游带我们参观了故宫。','Hướng dẫn viên dẫn chúng tôi tham quan Tử Cấm Thành.'],
  ['地球','trái đất','地球是我们的家。','Trái đất là nhà của chúng ta.'],
  ['地址','địa chỉ','请告诉我你的地址。','Xin cho tôi biết địa chỉ của bạn.'],
  ['动作','động tác','他的动作很标准。','Động tác của anh ấy rất chuẩn.'],
  ['肚子','bụng','我肚子饿了。','Tôi đói bụng.'],
  ['儿童','trẻ em','儿童喜欢玩游戏。','Trẻ em thích chơi trò chơi.'],
  ['法律','pháp luật','我们必须遵守法律。','Chúng ta phải tuân thủ pháp luật.'],
  ['范围','phạm vi','讨论的范围很广。','Phạm vi thảo luận rất rộng.'],
  ['方法','phương pháp','这个方法很有效。','Phương pháp này rất hiệu quả.'],
  ['风景','phong cảnh','这里的风景很美。','Phong cảnh ở đây rất đẹp.'],
  ['感觉','cảm giác','我感觉很好。','Tôi cảm thấy rất tốt.'],
  ['感情','tình cảm','他们的感情很深。','Tình cảm của họ rất sâu sắc.'],
  ['个子','chiều cao','他个子很高。','Anh ấy cao.'],
  ['工具','công cụ','这是很好的工具。','Đây là công cụ rất tốt.'],
  ['工资','lương','他的工资很高。','Lương của anh ấy rất cao.'],
  ['顾客','khách hàng','顾客很满意。','Khách hàng rất hài lòng.'],
  ['关键','chìa khóa','这是问题的关键。','Đây là chìa khóa của vấn đề.'],
  ['观众','khán giả','观众们很热情。','Khán giả rất nhiệt tình.'],
  ['广告','quảng cáo','这个广告很有创意。','Quảng cáo này rất sáng tạo.'],
  ['规定','quy định','请遵守规定。','Xin tuân thủ quy định.'],
  ['过程','quá trình','学习是一个过程。','Học tập là một quá trình.'],
  ['海洋','đại dương','海洋很广阔。','Đại dương rất rộng lớn.'],
  ['汗','mồ hôi','他出了一身汗。','Anh ấy đổ mồ hôi khắp người.'],
  ['航班','chuyến bay','航班延误了。','Chuyến bay bị trễ.'],
  ['好处','lợi ích','运动有很多好处。','Vận động có nhiều lợi ích.'],
  ['号码','số','你的电话号码是多少？','Số điện thoại của bạn là bao nhiêu?'],
  ['盒子','hộp','盒子里有什么？','Trong hộp có gì?'],
  ['猴子','con khỉ','猴子很聪明。','Con khỉ rất thông minh.'],
  ['护士','y tá','护士很细心。','Y tá rất cẩn thận.'],
  ['基础','nền tảng','这是学习的基础。','Đây là nền tảng của việc học.'],
  ['计划','kế hoạch','我们有一个新计划。','Chúng tôi có một kế hoạch mới.'],
  ['记者','phóng viên','记者正在采访。','Phóng viên đang phỏng vấn.'],
  ['技术','kỹ thuật','他的技术很好。','Kỹ thuật của anh ấy rất tốt.'],
  ['加油站','trạm xăng','前面有一个加油站。','Phía trước có một trạm xăng.'],
  ['家具','đồ nội thất','我们买了新家具。','Chúng tôi đã mua đồ nội thất mới.'],
  ['价格','giá','这个价格合理吗？','Giá này có hợp lý không?'],
  ['奖金','tiền thưởng','他得到了奖金。','Anh ấy nhận được tiền thưởng.'],
  ['交通','giao thông','交通很拥挤。','Giao thông rất đông đúc.'],
  ['饺子','bánh bao','她特别爱吃饺子。','Cô ấy đặc biệt thích ăn bánh bao.'],
  ['教授','giáo sư','这位教授很受学生们欢迎。','Giáo sư này rất được học sinh yêu mến.'],
  ['结果','kết quả','结果很好。','Kết quả rất tốt.'],
  ['京剧','Kinh kịch','我喜欢看京剧。','Tôi thích xem Kinh kịch.'],
  ['经济','kinh tế','经济发展很快。','Kinh tế phát triển rất nhanh.'],
  ['经历','kinh nghiệm','他有很多经历。','Anh ấy có nhiều kinh nghiệm.'],
  ['警察','cảnh sát','警察维护秩序。','Cảnh sát duy trì trật tự.'],
  ['镜子','gương','镜子里是谁？','Trong gương là ai?'],
  ['距离','khoảng cách','距离不远。','Khoảng cách không xa.'],
  ['看法','quan điểm','你的看法是什么？','Quan điểm của bạn là gì?'],
  ['空气','không khí','空气很新鲜。','Không khí rất trong lành.'],
  ['垃圾桶','thùng rác','请把垃圾扔到垃圾桶里。','Xin vứt rác vào thùng rác.'],
  ['老虎','con hổ','老虎是森林之王。','Hổ là vua của rừng.'],
  ['理想','lý tưởng','他有远大的理想。','Anh ấy có lý tưởng lớn.'],
  ['力气','sức lực','我没有力气了。','Tôi hết sức rồi.'],
  ['律师','luật sư','律师帮他打官司。','Luật sư giúp anh ấy kiện tụng.'],
  ['毛巾','khăn tắm','请把毛巾拿来。','Xin mang khăn tắm đến.'],
  ['梦','giấc mơ','我做了一个好梦。','Tôi mơ một giấc mơ đẹp.'],
  ['密码','mật khẩu','请输入密码。','Xin nhập mật khẩu.'],
  ['民族','dân tộc','中国有五十六个民族。','Trung Quốc có 56 dân tộc.'],
  ['目的','mục đích','你的目的是什么？','Mục đích của bạn là gì?'],
  ['内容','nội dung','内容很丰富。','Nội dung rất phong phú.'],
  ['能力','năng lực','他有能力完成。','Anh ấy có năng lực hoàn thành.'],
  ['年龄','tuổi','你的年龄多大？','Bạn bao nhiêu tuổi?'],
  ['农村','nông thôn','农村发展很快。','Nông thôn phát triển rất nhanh.'],
  ['皮肤','da','她的皮肤很白。','Da cô ấy rất trắng.'],
  ['脾气','tính khí','他脾气很好。','Tính khí anh ấy rất tốt.'],
  ['乒乓球','bóng bàn','我喜欢打乒乓球。','Tôi thích chơi bóng bàn.'],
  ['瓶子','chai','瓶子里有水。','Trong chai có nước.'],
  ['气候','khí hậu','这里的气候很好。','Khí hậu ở đây rất tốt.'],
  ['签证','thị thực','我需要办签证。','Tôi cần làm thị thực.'],
  ['墙','tường','墙上有一幅画。','Trên tường có một bức tranh.'],
  ['桥','cầu','这座桥很长。','Cây cầu này rất dài.'],
  ['巧克力','sô-cô-la','她喜欢吃巧克力。','Cô ấy thích ăn sô-cô-la.'],
  ['亲戚','họ hàng','春节要去看望亲戚。','Tết phải đi thăm họ hàng.'],
  ['情况','tình hình','情况怎么样？','Tình hình thế nào?'],
  ['区别','sự khác biệt','这两者有什么区别？','Hai thứ này có sự khác biệt gì?'],
  ['缺点','khuyết điểm','每个人都有缺点。','Mỗi người đều có khuyết điểm.'],
  ['人民币','nhân dân tệ','请用人民币付款。','Xin thanh toán bằng nhân dân tệ.'],
  ['任务','nhiệm vụ','任务完成了。','Nhiệm vụ đã hoàn thành.'],
  ['日记','nhật ký','她每天写日记。','Cô ấy viết nhật ký mỗi ngày.'],
  ['入口','lối vào','入口在那边。','Lối vào ở phía đó.'],
  ['森林','rừng','森林里有很多动物。','Trong rừng có nhiều động vật.'],
  ['沙发','ghế sofa','请坐在沙发上。','Xin ngồi trên ghế sofa.'],
  ['社会','xã hội','社会在进步。','Xã hội đang tiến bộ.'],
  ['生命','sinh mệnh','生命很宝贵。','Sinh mệnh rất quý giá.'],
  ['狮子','sư tử','狮子很凶猛。','Sư tử rất hung dữ.'],
  ['食品','thực phẩm','这些食品很新鲜。','Thực phẩm này rất tươi.'],
  ['市场','chợ','市场人很多。','Chợ đông người.'],
  ['收入','thu nhập','他的收入增加了。','Thu nhập của anh ấy tăng lên.'],
  ['首都','thủ đô','北京是中国的首都。','Bắc Kinh là thủ đô của Trung Quốc.'],
  ['售货员','nhân viên bán hàng','售货员很热情。','Nhân viên bán hàng rất nhiệt tình.'],
  ['数量','số lượng','数量很多。','Số lượng rất nhiều.'],
  ['数字','con số','这些数字很重要。','Những con số này rất quan trọng.'],
  // Additional nouns from PDF
  ['顺序','thứ tự','请按顺序排队。','Xin xếp hàng theo thứ tự.'],
  ['硕士','thạc sĩ','她是一名硕士。','Cô ấy là thạc sĩ.'],
  ['速度','tốc độ','速度太快了。','Tốc độ quá nhanh.'],
  ['酸','vị chua','这个橘子很酸。','Quả cam này rất chua.'],
  ['态度','thái độ','他的态度很好。','Thái độ của anh ấy rất tốt.'],
  ['汤','canh','这碗汤很好喝。','Bát canh này rất ngon.'],
  ['特点','đặc điểm','这是它的特点。','Đây là đặc điểm của nó.'],
  ['条件','điều kiện','条件很好。','Điều kiện rất tốt.'],
  ['通知','thông báo','请看一下通知。','Xin xem thông báo.'],
  ['袜子','tất','我买了一双袜子。','Tôi mua một đôi tất.'],
  ['网球','quần vợt','他喜欢打网球。','Anh ấy thích chơi quần vợt.'],
  ['网站','trang web','这个网站很有用。','Trang web này rất hữu ích.'],
  ['味道','hương vị','味道很好。','Hương vị rất tốt.'],
  ['温度','nhiệt độ','今天温度很低。','Hôm nay nhiệt độ rất thấp.'],
  ['西红柿','cà chua','西红柿都卖完了。','Cà chua đã bán hết.'],
  ['洗衣机','máy giặt','洗衣机坏了。','Máy giặt hỏng rồi.'],
  ['消息','tin tức','有好消息！','Có tin tốt!'],
  ['小说','tiểu thuyết','这本小说很有趣。','Cuốn tiểu thuyết này rất thú vị.'],
  ['笑话','truyện cười','他讲了一个笑话。','Anh ấy kể một truyện cười.'],
  ['效果','hiệu quả','效果很好。','Hiệu quả rất tốt.'],
  ['心情','tâm trạng','今天心情很好。','Hôm nay tâm trạng rất tốt.'],
  ['信心','sự tự tin','我很有信心。','Tôi rất tự tin.'],
  ['信用卡','thẻ tín dụng','请刷信用卡。','Xin quẹt thẻ tín dụng.'],
  ['性别','giới tính','请填写性别。','Xin điền giới tính.'],
  ['性格','tính cách','他的性格很活泼。','Tính cách anh ấy rất hoạt bát.'],
  ['血','máu','他流了很多血。','Anh ấy mất nhiều máu.'],
  ['压力','áp lực','工作压力很大。','Áp lực công việc rất lớn.'],
  ['牙膏','kem đánh răng','牙膏用完了。','Kem đánh răng hết rồi.'],
  ['研究生','nghiên cứu sinh','他是一名研究生。','Anh ấy là nghiên cứu sinh.'],
  ['盐','muối','请加点盐。','Xin cho thêm muối.'],
  ['演员','diễn viên','他是一位演员。','Anh ấy là diễn viên.'],
  ['阳光','ánh nắng','阳光很温暖。','Ánh nắng rất ấm áp.'],
  ['样子','dáng vẻ','你什么样子？','Bạn trông thế nào?'],
  ['艺术','nghệ thuật','这是真正的艺术。','Đây là nghệ thuật thực sự.'],
  ['意见','ý kiến','你有什么意见？','Bạn có ý kiến gì?'],
  ['饮料','đồ uống','请买两瓶饮料。','Xin mua hai chai đồ uống.'],
  ['印象','ấn tượng','印象很深。','Ấn tượng rất sâu.'],
  ['优点','ưu điểm','他有很多优点。','Anh ấy có nhiều ưu điểm.'],
  ['友谊','tình bạn','我们的友谊很深。','Tình bạn của chúng tôi rất sâu.'],
  ['羽毛球','cầu lông','我喜欢打羽毛球。','Tôi thích chơi cầu lông.'],
  ['语法','ngữ pháp','语法很重要。','Ngữ pháp rất quan trọng.'],
  ['语言','ngôn ngữ','汉语是一门美丽的语言。','Tiếng Trung là một ngôn ngữ đẹp.'],
  ['原因','nguyên nhân','原因找到了。','Đã tìm ra nguyên nhân.'],
  ['钥匙','chìa khóa','你忘记把钥匙放哪儿了。','Bạn quên để chìa khóa ở đâu rồi.'],
  ['杂志','tạp chí','我在看杂志。','Tôi đang đọc tạp chí.'],
  ['责任','trách nhiệm','这是你的责任。','Đây là trách nhiệm của bạn.'],
  ['知识','kiến thức','知识就是力量。','Tri thức là sức mạnh.'],
  ['职业','nghề nghiệp','你的职业是什么？','Nghề nghiệp của bạn là gì?'],
  ['植物','thực vật','这种植物很漂亮。','Loại thực vật này rất đẹp.'],
  ['质量','chất lượng','质量还可以。','Chất lượng còn được.'],
  ['重点','trọng điểm','这是重点。','Đây là trọng điểm.'],
  ['注意','chú ý','请注意安全。','Xin chú ý an toàn.'],
  ['专业','chuyên ngành','你的专业是什么？','Chuyên ngành của bạn là gì?'],
  ['自然','tự nhiên','大自然很美丽。','Thiên nhiên rất đẹp.'],
  ['组织','tổ chức','他们组织了这次活动。','Họ đã tổ chức hoạt động này.'],
  ['座位','ghế ngồi','请找座位坐下。','Xin tìm ghế ngồi.'],
]

export const verbs = [
  ['表扬','khen ngợi','因为考了第一，老师表扬了他。','Vì thi đứng nhất, giáo viên đã khen anh ấy.'],
  ['干杯','cạn ly','来，为我们的事业干杯！','Nào, cạn ly vì sự nghiệp của chúng ta!'],
  ['请客','mời khách','今天我请客。','Hôm nay tôi mời.'],
  ['同情','đồng cảm','大家很同情他。','Mọi người rất đồng cảm với anh ấy.'],
  ['养成','hình thành','我们应该养成良好的学习习惯。','Chúng ta nên hình thành thói quen học tập tốt.'],
  ['安排','sắp xếp','这次活动已经安排好了。','Hoạt động này đã được sắp xếp xong.'],
  ['包括','bao gồm','这次考试包括笔试和口试两部分。','Kỳ thi này bao gồm hai phần: viết và nói.'],
  ['保护','bảo vệ','保护环境是每个人的责任。','Bảo vệ môi trường là trách nhiệm của mỗi người.'],
  ['保证','đảm bảo','我保证下次再也不迟到了。','Tôi đảm bảo lần sau không đến muộn nữa.'],
  ['报名','đăng ký','这次考试我已经报名了。','Kỳ thi này tôi đã đăng ký rồi.'],
  ['毕业','tốt nghiệp','他毕业于北京大学。','Anh ấy tốt nghiệp Đại học Bắc Kinh.'],
  ['擦','lau','校长正在擦玻璃。','Hiệu trưởng đang lau kính.'],
  ['猜','đoán','你猜对了。','Bạn đoán đúng rồi.'],
  ['参观','tham quan','我昨天参观了他们公司。','Hôm qua tôi đã tham quan công ty họ.'],
  ['尝','nếm','你尝一尝这道菜怎么样？','Bạn nếm thử món này thế nào?'],
  ['乘坐','đi (phương tiện)','欢迎大家乘坐本次航班。','Chào mừng mọi người đi chuyến bay này.'],
  ['抽烟','hút thuốc','抽烟有害健康。','Hút thuốc có hại cho sức khỏe.'],
  ['出差','công tác','他经常去外地出差。','Anh ấy thường đi công tác ngoài tỉnh.'],
  ['出发','khởi hành','我打算6点从家里出发。','Tôi định khởi hành từ nhà lúc 6 giờ.'],
  ['出生','sinh ra','她出生于一个医生家庭。','Cô ấy sinh ra trong gia đình bác sĩ.'],
  ['打扮','trang điểm','今天她打扮得特别漂亮。','Hôm nay cô ấy trang điểm rất đẹp.'],
  ['打扰','làm phiền','现在是午休时间，别去打扰别人。','Giờ nghỉ trưa, đừng làm phiền người khác.'],
  ['打印','in','他正在打印一份材料。','Anh ấy đang in một tài liệu.'],
  ['打折','giảm giá','现在商场正在打折。','Bây giờ trung tâm thương mại đang giảm giá.'],
  ['打针','tiêm','小时候我最怕去医院打针了。','Hồi nhỏ tôi sợ nhất là đi bệnh viện tiêm.'],
  ['戴','đeo','他戴着一副黑色眼镜。','Anh ấy đeo kính đen.'],
  ['代替','thay thế','我代替她参加比赛。','Tôi thay cô ấy tham gia cuộc thi.'],
  ['道歉','xin lỗi','我真心向你道歉。','Tôi chân thành xin lỗi bạn.'],
  ['堵车','tắc đường','北京的交通状况不好，经常堵车。','Giao thông Bắc Kinh không tốt, thường tắc đường.'],
  ['翻译','dịch','他正在翻译一本英文小说。','Anh ấy đang dịch một tiểu thuyết tiếng Anh.'],
  ['反对','phản đối','他反对举行这次比赛。','Anh ấy phản đối tổ chức cuộc thi này.'],
  ['反映','phản ánh','考试成绩反映了学生平时的学习情况。','Điểm thi phản ánh tình hình học tập hàng ngày.'],
  ['访问','thăm','王经理正在美国访问。','Giám đốc Vương đang thăm Mỹ.'],
  ['放弃','từ bỏ','她放弃了这次比赛。','Cô ấy từ bỏ cuộc thi này.'],
  ['符合','phù hợp','产品一定要符合消费者的要求。','Sản phẩm phải phù hợp yêu cầu người tiêu dùng.'],
  ['复印','photocopy','我正在复印一些资料。','Tôi đang photocopy một số tài liệu.'],
  ['负责','phụ trách','他负责此次活动。','Anh ấy phụ trách hoạt động này.'],
  ['改变','thay đổi','他只好改变今天的计划。','Anh ấy buộc phải thay đổi kế hoạch hôm nay.'],
  ['感动','cảm động','大家的帮助让小王非常感动。','Sự giúp đỡ của mọi người khiến Tiểu Vương rất cảm động.'],
  ['购物','mua sắm','女孩子都喜欢逛街购物。','Con gái đều thích đi mua sắm.'],
  ['估计','ước tính','我估计这次考试不会太难。','Tôi ước tính kỳ thi này không quá khó.'],
  ['鼓励','khuyến khích','老师鼓励我多跟中国人交流。','Giáo viên khuyến khích tôi giao lưu với người Trung Quốc.'],
  ['鼓掌','vỗ tay','大家都在为他的精彩表演鼓掌。','Mọi người đều vỗ tay cho màn biểu diễn xuất sắc.'],
  ['挂','treo','墙上挂着一张画。','Trên tường treo một bức tranh.'],
  ['逛','dạo','学了一天了，我想出去逛逛。','Học cả ngày rồi, tôi muốn ra ngoài dạo.'],
  ['合格','đạt chuẩn','这些产品质量都不合格。','Chất lượng sản phẩm này đều không đạt chuẩn.'],
  ['后悔','hối hận','考试时他很后悔没认真复习。','Khi thi anh ấy rất hối hận vì không ôn bài.'],
  ['怀疑','nghi ngờ','老师怀疑他是来替人考试的。','Giáo viên nghi ngờ anh ấy thi thay.'],
  ['回忆','hồi tưởng','我经常回忆在北京留学的生活。','Tôi thường hồi tưởng cuộc sống du học ở Bắc Kinh.'],
  ['获得','đạt được','他获得了成功。','Anh ấy đã đạt được thành công.'],
  ['积累','tích lũy','他积累了很多经验。','Anh ấy tích lũy nhiều kinh nghiệm.'],
  ['集合','tập hợp','明天八点在校门口集合。','Ngày mai 8 giờ tập hợp ở cổng trường.'],
  ['寄','gửi','我给家里寄了一封信。','Tôi gửi một bức thư về nhà.'],
  ['继续','tiếp tục','这个周末还要继续加班。','Cuối tuần này vẫn phải tiếp tục làm thêm.'],
  ['坚持','kiên trì','他每天都坚持跑步。','Anh ấy mỗi ngày đều kiên trì chạy bộ.'],
  ['交','nộp','大家把作业交上去了。','Mọi người đã nộp bài tập.'],
  ['交流','giao lưu','大家经常交流学习经验。','Mọi người thường giao lưu kinh nghiệm học tập.'],
  ['接受','chấp nhận','我不能接受他的要求。','Tôi không thể chấp nhận yêu cầu của anh ấy.'],
  ['节约','tiết kiệm','大家要节约用水。','Mọi người hãy tiết kiệm nước.'],
  ['解释','giải thích','老师，您能解释一下这个词的意思吗？','Thầy ơi, thầy giải thích từ này được không?'],
  ['进行','tiến hành','会议正在进行。','Cuộc họp đang tiến hành.'],
  ['禁止','cấm','教室里禁止吸烟。','Trong lớp cấm hút thuốc.'],
  ['竞争','cạnh tranh','成功者不怕竞争。','Người thành công không sợ cạnh tranh.'],
  ['举办','tổ chức','学校要举办一次晚会。','Trường sẽ tổ chức một buổi tiệc.'],
  ['拒绝','từ chối','我拒绝了他的要求。','Tôi từ chối yêu cầu của anh ấy.'],
  ['考虑','cân nhắc','多考虑考虑别人。','Hãy cân nhắc người khác nhiều hơn.'],
  ['咳嗽','ho','他生病了，一直在咳嗽。','Anh ấy bị ốm, ho liên tục.'],
  ['可怜','đáng thương','大家很可怜他。','Mọi người rất thương anh ấy.'],
  ['可惜','đáng tiếc','可惜我有伤不能参加。','Đáng tiếc tôi bị thương không tham gia được.'],
  ['肯定','khẳng định','老师肯定了他的进步。','Giáo viên khẳng định sự tiến bộ của anh ấy.'],
  ['来不及','không kịp','再不出发的话，就来不及上车了。','Không khởi hành nữa thì không kịp lên xe.'],
  ['来得及','kịp','来得及，还有三个小时呢。','Còn kịp, còn ba tiếng nữa.'],
  ['浪费','lãng phí','这样做完全是浪费时间。','Làm vậy hoàn toàn lãng phí thời gian.'],
  ['理发','cắt tóc','头发都这么长了，该去理发了吧。','Tóc dài thế rồi, nên đi cắt tóc.'],
  ['理解','hiểu','我很理解他。','Tôi rất hiểu anh ấy.'],
  ['联系','liên lạc','毕业后同学们很少跟我联系。','Sau khi tốt nghiệp bạn bè ít liên lạc với tôi.'],
  ['聊天','trò chuyện','他喜欢在网上跟人聊天。','Anh ấy thích trò chuyện trên mạng.'],
  ['留学','du học','他来中国留学已经三年了。','Anh ấy du học Trung Quốc đã ba năm.'],
  ['流泪','rơi lệ','看电影的时候经常流泪。','Xem phim thường rơi lệ.'],
  ['流行','phổ biến','以前很流行这种打扮。','Trước đây kiểu trang điểm này rất phổ biến.'],
  ['免费','miễn phí','这些礼物都是免费的。','Những món quà này đều miễn phí.'],
  ['陪','đi cùng','我常陪小红去逛街。','Tôi thường đi mua sắm cùng Tiểu Hồng.'],
  ['批评','phê bình','这次考试我被老师批评了。','Kỳ thi này tôi bị giáo viên phê bình.'],
  ['骗','lừa','小东老骗人。','Tiểu Đông hay lừa người.'],
  ['起飞','cất cánh','开往北京的航班已经起飞了。','Chuyến bay đi Bắc Kinh đã cất cánh.'],
  ['敲','gõ','敲门的时候要有礼貌。','Gõ cửa phải lịch sự.'],
  ['商量','bàn bạc','我想跟大家商量商量考试的事情。','Tôi muốn bàn bạc chuyện thi với mọi người.'],
  ['失败','thất bại','虽然这次我失败了，但我并没有失去信心。','Dù thất bại lần này, tôi không mất niềm tin.'],
  ['适合','phù hợp','这件衣服肯定适合你。','Bộ quần áo này chắc hợp với bạn.'],
  ['适应','thích nghi','我已经适应了这里的生活。','Tôi đã thích nghi cuộc sống ở đây.'],
  ['收拾','dọn dẹp','赶紧把家里的衣服收拾收拾。','Mau dọn quần áo trong nhà.'],
  ['熟悉','quen thuộc','他很熟悉这所大学。','Anh ấy rất quen với trường đại học này.'],
  ['信任','tin tưởng','经理非常信任小张。','Giám đốc rất tin tưởng Tiểu Trương.'],
  ['预习','ôn trước','学习新课前希望大家能预习一下课文。','Trước khi học bài mới mong mọi người ôn trước.'],
  ['约会','hẹn hò','今天晚上我要跟小张约会。','Tối nay tôi hẹn hò với Tiểu Trương.'],
  ['招聘','tuyển dụng','这个公司正在招聘员工。','Công ty này đang tuyển dụng nhân viên.'],
  ['重视','coi trọng','父母们非常重视孩子的教育问题。','Cha mẹ rất coi trọng giáo dục con.'],
  ['赚','kiếm tiền','他的事业很成功，赚了很多钱。','Sự nghiệp anh ấy thành công, kiếm nhiều tiền.'],
  ['租','thuê','我想租一辆车。','Tôi muốn thuê một chiếc xe.'],
]

export const adjectives = [
  ['暖和','ấm áp','今年冬天特别暖和。','Mùa đông năm nay đặc biệt ấm áp.'],
  ['凉快','mát mẻ','今天挺凉快的。','Hôm nay khá mát.'],
  ['有趣','thú vị','这本小说挺有趣的。','Cuốn tiểu thuyết này khá thú vị.'],
  ['成熟','trưởng thành','她很成熟，做事情大家都放心。','Cô ấy rất trưởng thành, mọi người đều yên tâm.'],
  ['诚实','thành thật','她很诚实，从来不说假话。','Cô ấy rất thành thật, không bao giờ nói dối.'],
  ['活泼','hoạt bát','他的性格非常活泼。','Tính cách anh ấy rất hoạt bát.'],
  ['伤心','buồn','他没拿到签证，很伤心。','Anh ấy không có visa, rất buồn.'],
  ['吃惊','ngạc nhiên','大家都吃惊。','Mọi người đều ngạc nhiên.'],
  ['得意','đắc ý','她非常得意，到处跟人说。','Cô ấy rất đắc ý, kể khắp nơi.'],
  ['丰富','phong phú','他的感情很丰富。','Tình cảm anh ấy rất phong phú.'],
  ['复杂','phức tạp','这台机器太复杂了。','Cái máy này quá phức tạp.'],
  ['害羞','nhút nhát','她很害羞，不敢跟男生说话。','Cô ấy rất nhút nhát, không dám nói chuyện với con trai.'],
  ['厚','dày','怎么还穿这么厚的衣服？','Sao còn mặc quần áo dày thế?'],
  ['激动','xúc động','他非常激动。','Anh ấy rất xúc động.'],
  ['积极','tích cực','他在课堂上非常积极。','Trong lớp anh ấy rất tích cực.'],
  ['紧张','căng thẳng','我有点儿紧张。','Tôi hơi căng thẳng.'],
  ['精彩','xuất sắc','今天的表演非常精彩。','Buổi biểu diễn hôm nay rất xuất sắc.'],
  ['旧','cũ','你这衣服也太旧了。','Quần áo bạn cũ quá.'],
  ['困','buồn ngủ','今天上课的时候特儿困。','Hôm nay trên lớp buồn ngủ lắm.'],
  ['懒','lười','他是个懒学生。','Anh ấy là học sinh lười.'],
  ['冷静','bình tĩnh','遇到突发事件时一定要冷静。','Gặp sự cố phải bình tĩnh.'],
  ['流利','trôi chảy','他能说一口流利的汉语。','Anh ấy nói tiếng Trung rất trôi chảy.'],
  ['美丽','đẹp','这儿的景色非常美丽。','Phong cảnh ở đây rất đẹp.'],
  ['轻松','nhẹ nhàng','预习课文的同学上课时会很轻松。','Học sinh ôn bài trước sẽ nhẹ nhàng hơn.'],
  ['热闹','náo nhiệt','过春节的时候大街上非常热闹。','Tết đường phố rất náo nhiệt.'],
  ['软','mềm','只能吃软的东西。','Chỉ ăn được đồ mềm.'],
  ['顺利','thuận lợi','这次办签证非常顺利。','Lần này làm visa rất thuận lợi.'],
  ['无聊','nhàm chán','放假了，一个人在家很无聊。','Nghỉ lễ ở nhà một mình rất nhàm chán.'],
  ['详细','chi tiết','老师讲得很详细。','Giáo viên giảng rất chi tiết.'],
  ['严重','nghiêm trọng','他的病很严重。','Bệnh anh ấy rất nghiêm trọng.'],
  ['勇敢','dũng cảm','他很勇敢。','Anh ấy rất dũng cảm.'],
  ['脏','bẩn','快把房间收拾收拾，太脏了。','Mau dọn phòng, bẩn quá.'],
  ['窄','hẹp','这条路太窄了。','Con đường này quá hẹp.'],
  ['整齐','ngăn nắp','家里非常整齐。','Nhà rất ngăn nắp.'],
  ['正常','bình thường','一切都很正常。','Mọi thứ đều bình thường.'],
  ['正确','đúng','他的回答是正确的。','Câu trả lời của anh ấy đúng.'],
  ['著名','nổi tiếng','北京大学是中国最著名的大学。','Đại học Bắc Kinh là trường nổi tiếng nhất Trung Quốc.'],
  ['准确','chính xác','他的发音非常准确。','Phát âm anh ấy rất chính xác.'],
  ['仔细','cẩn thận','他做事情非常仔细。','Anh ấy làm việc rất cẩn thận.'],
  ['安全','an toàn','带很多钱不安全。','Mang nhiều tiền không an toàn.'],
  ['成功','thành công','奥运会非常成功。','Olympic rất thành công.'],
  ['干燥','khô','北京的冬天非常干燥。','Mùa đông Bắc Kinh rất khô.'],
  ['孤单','cô đơn','他一个人来北京留学，非常孤单。','Anh ấy du học một mình, rất cô đơn.'],
  ['骄傲','kiêu ngạo','他考了100分之后就变骄傲了。','Được 100 điểm anh ấy trở nên kiêu ngạo.'],
  ['苦','đắng','我不喜欢吃中药，太苦了。','Tôi không thích thuốc Trung Quốc, quá đắng.'],
  ['辣','cay','四川菜比较辣。','Món Tứ Xuyên khá cay.'],
  ['浪漫','lãng mạn','他非常浪漫。','Anh ấy rất lãng mạn.'],
  ['马虎','cẩu thả','他太马虎了，考试忘了写名字。','Anh ấy quá cẩu thả, thi quên viết tên.'],
  ['耐心','kiên nhẫn','我的老师很耐心。','Giáo viên tôi rất kiên nhẫn.'],
  ['危险','nguy hiểm','酒后开车很危险。','Lái xe sau khi uống rượu rất nguy hiểm.'],
  ['幽默','hài hước','他是个幽默的人。','Anh ấy là người hài hước.'],
]

export const adverbs = [
  ['按时','đúng giờ','他每天按时上班，从来不迟到。','Anh ấy đi làm đúng giờ, không bao giờ muộn.'],
  ['从来','từ trước đến nay','他从来不做运动。','Anh ấy từ trước đến nay không vận động.'],
  ['本来','vốn dĩ','我本来挺白的，后来晒黑了。','Vốn dĩ tôi trắng, sau bị đen.'],
  ['重新','lại','让我重新写一遍。','Cho tôi viết lại một lần.'],
  ['大概','khoảng','屋子里大概有四五十人。','Trong phòng khoảng bốn mươi đến năm mươi người.'],
  ['到处','khắp nơi','街上到处都是人。','Trên đường khắp nơi đều có người.'],
  ['刚刚','vừa mới','王经理刚刚出差回来。','Giám đốc Vương vừa mới đi công tác về.'],
  ['共同','cùng nhau','两所大学共同申请。','Hai trường đại học cùng nhau đăng ký.'],
  ['故意','cố ý','我故意不理她。','Tôi cố ý không để ý cô ấy.'],
  ['果然','quả nhiên','下午果然下起雨来。','Buổi chiều quả nhiên mưa.'],
  ['互相','lẫn nhau','同学之间应该互相帮助。','Bạn bè nên giúp đỡ lẫn nhau.'],
  ['极其','cực kỳ','这个老师的要求极其严格。','Yêu cầu giáo viên này cực kỳ nghiêm.'],
  ['竟然','lại','这次考试竟然会这么简单。','Kỳ thi này lại đơn giản thế.'],
  ['究竟','rốt cuộc','究竟出了什么事？','Rốt cuộc có chuyện gì?'],
  ['恐怕','e rằng','恐怕是真出事了。','E rằng thật sự có chuyện.'],
  ['也许','có lẽ','也许是生病了。','Có lẽ bị ốm.'],
  ['难道','lẽ nào','你难道还不明白？','Lẽ nào bạn chưa hiểu?'],
  ['偶尔','thỉnh thoảng','偶尔也打打乒乓球。','Thỉnh thoảng cũng chơi bóng bàn.'],
  ['仍然','vẫn','他仍然是那么受欢迎。','Anh ấy vẫn được yêu mến như vậy.'],
  ['实在','thật sự','我实在想不起来他的名字。','Tôi thật sự không nhớ tên anh ấy.'],
  ['顺便','tiện thể','你这次出国顺便给我买个电脑。','Lần đi nước ngoài này tiện mua máy tính giúp tôi.'],
  ['往往','thường','聪明人往往会犯一些简单的错误。','Người thông minh thường mắc lỗi đơn giản.'],
  ['永远','mãi mãi','永远都不会成功。','Mãi mãi không thành công.'],
  ['尤其','đặc biệt','尤其是写作课，经常得满分。','Đặc biệt môn viết, thường được điểm tối đa.'],
  ['原来','hóa ra','原来你是生病休学了。','Hóa ra bạn nghỉ học vì bị ốm.'],
  ['暂时','tạm thời','他暂时不想看书了。','Anh ấy tạm thời không muốn đọc sách.'],
  ['只好','đành phải','他只好退学了。','Anh ấy đành phải bỏ học.'],
  ['至少','ít nhất','四级至少要考到180分。','HSK4 ít nhất phải 180 điểm.'],
  ['逐渐','dần dần','他的听力水平逐渐有了提高。','Trình độ nghe của anh ấy dần cải thiện.'],
  ['专门','chuyên','留学生办公室是专门为留学服务的。','Văn phòng du học sinh chuyên phục vụ du học.'],
  ['最好','tốt nhất','明天最好别刮大风。','Ngày mai tốt nhất đừng gió lớn.'],
  ['好像','hình như','他妈妈好像是老师。','Mẹ anh ấy hình như là giáo viên.'],
]

export const conjunctions = [
  ['无论','dù','无论遇到什么困难，我都不会放弃。','Dù gặp khó khăn gì, tôi cũng không từ bỏ.'],
  ['尽管','mặc dù','尽管这个公司不大，却非常赚钱。','Mặc dù công ty nhỏ nhưng rất kiếm tiền.'],
  ['否则','nếu không','你必须办好护照和签证，否则出不了国。','Phải làm hộ chiếu và visa, nếu không không ra nước ngoài được.'],
  ['另外','ngoài ra','多带点儿钱，另外把信用卡也带上。','Mang thêm tiền, ngoài ra mang thẻ tín dụng.'],
  ['其次','thứ hai','其次才是易建联。','Thứ hai mới là Diệp Kiện Lian.'],
  ['然而','tuy nhiên','他很富有，然而并不快乐。','Anh ấy giàu nhưng không vui.'],
  ['不过','nhưng','这个菜味道不错，不过稍微咸了点儿。','Món này ngon nhưng hơi mặn.'],
  ['即使','ngay cả khi','即使明天下雨，我也要去踢球。','Ngay cả khi mai mưa, tôi vẫn đi đá bóng.'],
  ['既然','đã vậy','既然你不想去，就别去了。','Đã không muốn đi thì đừng đi.'],
]
